server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
          - id: second-service
            uri: lb://MY-SECOND-SERVICE
            predicates:
              - Path=/second-service/**
            filters:
              - CustomFilter
#              - AddRequestHeader=second-request, second-request-header2
#              - AddResponseHeader=second-response, second-response-header2
          - id: third-service
            uri: lb://MY-THIRD-SERVICE
            predicates:
              - Path=/third-service/**
            filters:
#              - AddRequestHeader=third-request, third-request-header2
#              - AddResponseHeader=third-response, third-response-header2
              - name: CustomFilter
              - name: LoggingFilter
                args:
                  baseMessage: Spring Cloud Gateway Global Filter
                  preLogger: true
                  postLogger: true

