server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
        routes:
          - id: second-service
            uri: http://localhost:8081/
            predicates:
              - Path=/second-service/**
            filters:
              - CustomFilter
#              - AddRequestHeader=second-request, second-request-header2
#              - AddResponseHeader=second-response, second-response-header2
          - id: third-service
            uri: http://localhost:8082/
            predicates:
              - Path=/third-service/**
            filters:
              - CustomFilter
#              - AddRequestHeader=third-request, third-request-header2
#              - AddResponseHeader=third-response, third-response-header2
