server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
  profiles:
    active: prod
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/actuator/**
              - Method=POST,GET
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/login
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/users
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/**
              - Method=GET
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
              - AuthorizationHeaderFilter
          - id: catalog-service
            uri: lb://CATALOG-SERVICE
            predicates:
              - Path=/catalog-service/**
#          - id: user-service
#            uri: lb://USER-SERVICE
#            predicates:
#              - Path=/user-service/**
#            filters:
#              - CustomFilter
          - id: second-service
            uri: lb://MY-SECOND-SERVICE
            predicates:
              - Path=/second-service/**
            filters:
              - CustomFilter
#              - AddRequestHeader=second-request, second-request-header2
#              - AddResponseHeader=second-response, second-response-header2
          - id: third-service
            uri: lb://MY-THIRD-SERVICE
            predicates:
              - Path=/third-service/**
            filters:
#              - AddRequestHeader=third-request, third-request-header2
#              - AddResponseHeader=third-response, third-response-header2
              - name: CustomFilter
              - name: LoggingFilter
                args:
                  baseMessage: Spring Cloud Gateway Global Filter
                  preLogger: true
                  postLogger: true

#token:
#  secret: z7N83jVxDfuNXAbhvX69I6+ENfpEhHzP0Mw6v/ukaTE=

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace