server:
  port: 0

spring:
  application:
    name: userservice
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${sppring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # default true
    fetch-registry: true # default true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # eureka server ? ??
